### PR TITLE
add sound level and motion level

### PR DESCRIPTION
**Pull request by goldserg**
Add 2 sensor type

### CODE REVIEW

**Comment by goldserg** [comment]
Hi, @efa2000 please look my PR.

**Comment by goldserg** [comment]
Hi, @efa2000 please look my PR.

**Comment by efa2000** [comment]
> Add 2 sensor type

Unfortunately that won't work.
You can only use the types of services supported by Yandex
[https://yandex.ru/dev/dialogs/smart-home/doc/concepts/float-instance.html](https://yandex.ru/dev/dialogs/smart-home/doc/concepts/float-instance.html)

sound_level, motion_level not supported

**Comment by goldserg** [comment]
Ok, I wrote to the yandex support for expand new types, will be wait...

**Pull request closed without merging**
